[package]
name = "my-supervisor-platform-macos"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "msv-log-proxy"
path = "src/bin/msv-log-proxy.rs"

[[bin]]
name = "msv-group-reaper"
path = "src/bin/msv-group-reaper.rs"

[dependencies]
my-supervisor-core = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
dirs = { workspace = true }
notify = { workspace = true }
libc = "0.2"
tokio = { version = "1", default-features = false, features = [
    "process",
    "fs",
    "io-util",
    "rt",
    "time",
    "sync",
    "macros",
    "net",
] }

[dev-dependencies]
my-supervisor-application = { workspace = true }
my-supervisor-config = { workspace = true }
my-supervisor-infra-logging = { workspace = true }
my-supervisor-infra-scheduler = { workspace = true }
my-supervisor-infra-sqlite = { workspace = true }
