[package]
name = "my-supervisor-infra-logging"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
my-supervisor-core = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tokio = { version = "1", default-features = false, features = ["sync", "fs", "io-util"] }

[dev-dependencies]
tokio = { workspace = true }
