[package]
name = "my-supervisor-app-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "my-supervisor"
path = "src/main.rs"

[package.metadata.msv-release]
architecture = "arm64-only"
target = "aarch64-apple-darwin"

[build-dependencies]
tauri-build = { version = "2", features = [] }
serde_json = { workspace = true }

[dependencies]
my-supervisor-core = { workspace = true }
my-supervisor-application = { workspace = true }
my-supervisor-shared = { workspace = true }
my-supervisor-app-daemon = { workspace = true }
my-supervisor-infra-http = { workspace = true }
tauri = { version = "2", features = ["tray-icon"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
